# coding: utf-8

# flake8: noqa
"""
    KNMI Data Platform - Open Data API

    For more information on the Open Data API and how to use it, visit the [Open Data API Documentation Page](https://developer.dataplatform.knmi.nl/open-data-api).

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.file_download import FileDownload
from openapi_client.models.file_summary import FileSummary
from openapi_client.models.list_files_response import ListFilesResponse

