# coding: utf-8

"""
    KNMI Data Platform - Open Data API

    For more information on the Open Data API and how to use it, visit the [Open Data API Documentation Page](https://developer.dataplatform.knmi.nl/open-data-api).

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_v1_datasets_dataset_name_versions_version_id_files_filename_url_get(self) -> None:
        """Test case for v1_datasets_dataset_name_versions_version_id_files_filename_url_get

        Get a temporary download URL for a dataset file
        """
        pass

    def test_v1_datasets_dataset_name_versions_version_id_files_get(self) -> None:
        """Test case for v1_datasets_dataset_name_versions_version_id_files_get

        Get paginated list of files for dataset
        """
        pass


if __name__ == '__main__':
    unittest.main()
