# coding: utf-8

"""
    KNMI Data Platform - Open Data API

    For more information on the Open Data API and how to use it, visit the [Open Data API Documentation Page](https://developer.dataplatform.knmi.nl/open-data-api).

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_files_response import ListFilesResponse

class TestListFilesResponse(unittest.TestCase):
    """ListFilesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListFilesResponse:
        """Test ListFilesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListFilesResponse`
        """
        model = ListFilesResponse()
        if include_optional:
            return ListFilesResponse(
                is_truncated = True,
                files = [
                    openapi_client.models.file_summary.FileSummary(
                        filename = '', 
                        last_modified = '', 
                        size = 56, 
                        created = '', )
                    ],
                result_count = 56,
                max_results = 56,
                start_after_filename = '',
                next_page_token = ''
            )
        else:
            return ListFilesResponse(
                is_truncated = True,
                files = [
                    openapi_client.models.file_summary.FileSummary(
                        filename = '', 
                        last_modified = '', 
                        size = 56, 
                        created = '', )
                    ],
                result_count = 56,
                max_results = 56,
                start_after_filename = '',
                next_page_token = '',
        )
        """

    def testListFilesResponse(self):
        """Test ListFilesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
