# coding: utf-8

"""
    KNMI Data Platform - Open Data API

    For more information on the Open Data API and how to use it, visit the [Open Data API Documentation Page](https://developer.dataplatform.knmi.nl/open-data-api).

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.file_summary import FileSummary

class TestFileSummary(unittest.TestCase):
    """FileSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileSummary:
        """Test FileSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileSummary`
        """
        model = FileSummary()
        if include_optional:
            return FileSummary(
                filename = '',
                last_modified = '',
                size = 56,
                created = ''
            )
        else:
            return FileSummary(
                filename = '',
                last_modified = '',
                size = 56,
                created = '',
        )
        """

    def testFileSummary(self):
        """Test FileSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
