# coding: utf-8

"""
    KNMI Data Platform - Open Data API

    For more information on the Open Data API and how to use it, visit the [Open Data API Documentation Page](https://developer.dataplatform.knmi.nl/open-data-api).

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.file_download import FileDownload
from openapi_client.models.list_files_response import ListFilesResponse

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class DefaultApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def download_files(
        self,
        dataset_name: Annotated[StrictStr, Field(description="Name of the dataset")],
        version_id: Annotated[StrictStr, Field(description="Version of the dataset")],
        filename: Annotated[StrictStr, Field(description="Name of the file")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> FileDownload:
        """Get a temporary download URL for a dataset file

        Get a temporary download URL for a dataset file

        :param dataset_name: Name of the dataset (required)
        :type dataset_name: str
        :param version_id: Version of the dataset (required)
        :type version_id: str
        :param filename: Name of the file (required)
        :type filename: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._download_files_serialize(
            dataset_name=dataset_name,
            version_id=version_id,
            filename=filename,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FileDownload",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def download_files_with_http_info(
        self,
        dataset_name: Annotated[StrictStr, Field(description="Name of the dataset")],
        version_id: Annotated[StrictStr, Field(description="Version of the dataset")],
        filename: Annotated[StrictStr, Field(description="Name of the file")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[FileDownload]:
        """Get a temporary download URL for a dataset file

        Get a temporary download URL for a dataset file

        :param dataset_name: Name of the dataset (required)
        :type dataset_name: str
        :param version_id: Version of the dataset (required)
        :type version_id: str
        :param filename: Name of the file (required)
        :type filename: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._download_files_serialize(
            dataset_name=dataset_name,
            version_id=version_id,
            filename=filename,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FileDownload",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def download_files_without_preload_content(
        self,
        dataset_name: Annotated[StrictStr, Field(description="Name of the dataset")],
        version_id: Annotated[StrictStr, Field(description="Version of the dataset")],
        filename: Annotated[StrictStr, Field(description="Name of the file")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get a temporary download URL for a dataset file

        Get a temporary download URL for a dataset file

        :param dataset_name: Name of the dataset (required)
        :type dataset_name: str
        :param version_id: Version of the dataset (required)
        :type version_id: str
        :param filename: Name of the file (required)
        :type filename: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._download_files_serialize(
            dataset_name=dataset_name,
            version_id=version_id,
            filename=filename,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "FileDownload",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _download_files_serialize(
        self,
        dataset_name,
        version_id,
        filename,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if dataset_name is not None:
            _path_params['datasetName'] = dataset_name
        if version_id is not None:
            _path_params['versionId'] = version_id
        if filename is not None:
            _path_params['filename'] = filename
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/datasets/{datasetName}/versions/{versionId}/files/{filename}/url',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_files(
        self,
        dataset_name: Annotated[StrictStr, Field(description="Name of the dataset")],
        version_id: Annotated[StrictStr, Field(description="Version of the dataset")],
        max_keys: Annotated[Optional[Annotated[int, Field(le=1000, strict=True)]], Field(description="Maximum number of files to return")] = None,
        sorting: Annotated[Optional[StrictStr], Field(description="Sort the files in ascending or descending order")] = None,
        order_by: Annotated[Optional[StrictStr], Field(description="Order the files by filename, timestamp of creation or timestamp of last modification")] = None,
        begin: Annotated[Optional[StrictStr], Field(description="This parameter controls filtering (together with end). It defines the lower limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).")] = None,
        end: Annotated[Optional[StrictStr], Field(description="This parameter controls filtering (together with begin). It defines the upper limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).")] = None,
        next_page_token: Annotated[Optional[StrictStr], Field(description="Token to retrieve the next page of results. This token is returned by the API if the result set is larger than the maximum number of files to return.")] = None,
        start_after_filename: Annotated[Optional[StrictStr], Field(description="Provide a filename to start listing after. Note: This deprecated parameter cannot be combined with orderBy, begin, end or sorting. Instead, use `nextPageToken`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListFilesResponse:
        """Get paginated list of files for dataset

        Get paginated list of files for dataset

        :param dataset_name: Name of the dataset (required)
        :type dataset_name: str
        :param version_id: Version of the dataset (required)
        :type version_id: str
        :param max_keys: Maximum number of files to return
        :type max_keys: int
        :param sorting: Sort the files in ascending or descending order
        :type sorting: str
        :param order_by: Order the files by filename, timestamp of creation or timestamp of last modification
        :type order_by: str
        :param begin: This parameter controls filtering (together with end). It defines the lower limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).
        :type begin: str
        :param end: This parameter controls filtering (together with begin). It defines the upper limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).
        :type end: str
        :param next_page_token: Token to retrieve the next page of results. This token is returned by the API if the result set is larger than the maximum number of files to return.
        :type next_page_token: str
        :param start_after_filename: Provide a filename to start listing after. Note: This deprecated parameter cannot be combined with orderBy, begin, end or sorting. Instead, use `nextPageToken`.
        :type start_after_filename: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_files_serialize(
            dataset_name=dataset_name,
            version_id=version_id,
            max_keys=max_keys,
            sorting=sorting,
            order_by=order_by,
            begin=begin,
            end=end,
            next_page_token=next_page_token,
            start_after_filename=start_after_filename,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListFilesResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_files_with_http_info(
        self,
        dataset_name: Annotated[StrictStr, Field(description="Name of the dataset")],
        version_id: Annotated[StrictStr, Field(description="Version of the dataset")],
        max_keys: Annotated[Optional[Annotated[int, Field(le=1000, strict=True)]], Field(description="Maximum number of files to return")] = None,
        sorting: Annotated[Optional[StrictStr], Field(description="Sort the files in ascending or descending order")] = None,
        order_by: Annotated[Optional[StrictStr], Field(description="Order the files by filename, timestamp of creation or timestamp of last modification")] = None,
        begin: Annotated[Optional[StrictStr], Field(description="This parameter controls filtering (together with end). It defines the lower limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).")] = None,
        end: Annotated[Optional[StrictStr], Field(description="This parameter controls filtering (together with begin). It defines the upper limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).")] = None,
        next_page_token: Annotated[Optional[StrictStr], Field(description="Token to retrieve the next page of results. This token is returned by the API if the result set is larger than the maximum number of files to return.")] = None,
        start_after_filename: Annotated[Optional[StrictStr], Field(description="Provide a filename to start listing after. Note: This deprecated parameter cannot be combined with orderBy, begin, end or sorting. Instead, use `nextPageToken`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListFilesResponse]:
        """Get paginated list of files for dataset

        Get paginated list of files for dataset

        :param dataset_name: Name of the dataset (required)
        :type dataset_name: str
        :param version_id: Version of the dataset (required)
        :type version_id: str
        :param max_keys: Maximum number of files to return
        :type max_keys: int
        :param sorting: Sort the files in ascending or descending order
        :type sorting: str
        :param order_by: Order the files by filename, timestamp of creation or timestamp of last modification
        :type order_by: str
        :param begin: This parameter controls filtering (together with end). It defines the lower limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).
        :type begin: str
        :param end: This parameter controls filtering (together with begin). It defines the upper limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).
        :type end: str
        :param next_page_token: Token to retrieve the next page of results. This token is returned by the API if the result set is larger than the maximum number of files to return.
        :type next_page_token: str
        :param start_after_filename: Provide a filename to start listing after. Note: This deprecated parameter cannot be combined with orderBy, begin, end or sorting. Instead, use `nextPageToken`.
        :type start_after_filename: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_files_serialize(
            dataset_name=dataset_name,
            version_id=version_id,
            max_keys=max_keys,
            sorting=sorting,
            order_by=order_by,
            begin=begin,
            end=end,
            next_page_token=next_page_token,
            start_after_filename=start_after_filename,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListFilesResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_files_without_preload_content(
        self,
        dataset_name: Annotated[StrictStr, Field(description="Name of the dataset")],
        version_id: Annotated[StrictStr, Field(description="Version of the dataset")],
        max_keys: Annotated[Optional[Annotated[int, Field(le=1000, strict=True)]], Field(description="Maximum number of files to return")] = None,
        sorting: Annotated[Optional[StrictStr], Field(description="Sort the files in ascending or descending order")] = None,
        order_by: Annotated[Optional[StrictStr], Field(description="Order the files by filename, timestamp of creation or timestamp of last modification")] = None,
        begin: Annotated[Optional[StrictStr], Field(description="This parameter controls filtering (together with end). It defines the lower limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).")] = None,
        end: Annotated[Optional[StrictStr], Field(description="This parameter controls filtering (together with begin). It defines the upper limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).")] = None,
        next_page_token: Annotated[Optional[StrictStr], Field(description="Token to retrieve the next page of results. This token is returned by the API if the result set is larger than the maximum number of files to return.")] = None,
        start_after_filename: Annotated[Optional[StrictStr], Field(description="Provide a filename to start listing after. Note: This deprecated parameter cannot be combined with orderBy, begin, end or sorting. Instead, use `nextPageToken`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get paginated list of files for dataset

        Get paginated list of files for dataset

        :param dataset_name: Name of the dataset (required)
        :type dataset_name: str
        :param version_id: Version of the dataset (required)
        :type version_id: str
        :param max_keys: Maximum number of files to return
        :type max_keys: int
        :param sorting: Sort the files in ascending or descending order
        :type sorting: str
        :param order_by: Order the files by filename, timestamp of creation or timestamp of last modification
        :type order_by: str
        :param begin: This parameter controls filtering (together with end). It defines the lower limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).
        :type begin: str
        :param end: This parameter controls filtering (together with begin). It defines the upper limit of the requested data. If ordering by filename, provide a string. If ordering by lastModified or created, provide a timestamp in ISO8601 format with a timezone (e.g. 2022-01-01T00:00:00Z).
        :type end: str
        :param next_page_token: Token to retrieve the next page of results. This token is returned by the API if the result set is larger than the maximum number of files to return.
        :type next_page_token: str
        :param start_after_filename: Provide a filename to start listing after. Note: This deprecated parameter cannot be combined with orderBy, begin, end or sorting. Instead, use `nextPageToken`.
        :type start_after_filename: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_files_serialize(
            dataset_name=dataset_name,
            version_id=version_id,
            max_keys=max_keys,
            sorting=sorting,
            order_by=order_by,
            begin=begin,
            end=end,
            next_page_token=next_page_token,
            start_after_filename=start_after_filename,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListFilesResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_files_serialize(
        self,
        dataset_name,
        version_id,
        max_keys,
        sorting,
        order_by,
        begin,
        end,
        next_page_token,
        start_after_filename,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if dataset_name is not None:
            _path_params['datasetName'] = dataset_name
        if version_id is not None:
            _path_params['versionId'] = version_id
        # process the query parameters
        if max_keys is not None:
            
            _query_params.append(('maxKeys', max_keys))
            
        if sorting is not None:
            
            _query_params.append(('sorting', sorting))
            
        if order_by is not None:
            
            _query_params.append(('orderBy', order_by))
            
        if begin is not None:
            
            _query_params.append(('begin', begin))
            
        if end is not None:
            
            _query_params.append(('end', end))
            
        if next_page_token is not None:
            
            _query_params.append(('nextPageToken', next_page_token))
            
        if start_after_filename is not None:
            
            _query_params.append(('startAfterFilename', start_after_filename))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/datasets/{datasetName}/versions/{versionId}/files',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


